### ISSUE TITLE
liquibase-core leaks the classloader

### ISSUE THREAD

**Issue by ArloL** [spring-io/platform#128]
See [CORE-2182](https://liquibase.jira.com/browse/CORE-2182) for details.

Is there documentation as to how the platform bom is tested?

I have test code that checks for classloader leaks. Maybe it can be integrated to prevent issues like this in future (even for other dependencies).

**Comment by wilkinsona** [comment]
Spring Boot determines the version of Liquibase that's in the Platform, and also has the Liquibase-related tests. I've opened a Spring Boot issue to track this (see above).
