### ISSUE TITLE
org.hibernate.javax.persistence:hibernate-jpa-2.0-api:1.0.1.Final is incompatible with org.hibernate:hibernate-core:4.3.7.Final

### ISSUE THREAD

**Issue by rdehuyss** [spring-io/platform#146]
Hi all,

In Hibernate 4.3.7, the class EntityBinder makes use of SecondaryTable.indexes() method (line 849).

The method SecondaryTable.indexes() is only available in hibernate-jpa-2.1-api and not in hibernate-jpa-2.0-api. This results in a NoSuchMethod runtime exception.

Can you update the dependency to 2.1?

Thanks,
Ronald

**Comment by wilkinsona** [comment]
The Platform's in a slightly odd place with JPA as the projects it includes support both JPA 2.0 and JPA 2.1. We can't easily move the dependency you've mentioned to 2.1 as its got its version included in the artifact id, i.e. `org.hibernate.javax.persistence:hibernate-jpa-2.0-api` is a totally separate artifact to `org.hibernate.javax.persistence:hibernate-jpa-2.1-api`. If we remove the former in favour of the latter, we may break existing applications that use JPA 2.0.

If you're looking for a JPA API jar to depend upon in your application then please use `org.eclipse.persistence:javax.persistence` which is part of the Platform and doesn't include a version in its artifact id making version upgrades far more straightforward.
