### ISSUE TITLE
Spring IO 1.1.1.RELEASE 'asks for' org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by manueljordan** [spring-io/platform#151]
Hello

I am working with: 

- Maven 
- STS 3.6.3.SR1
- JDK 8u31.

I have many modules (repositories, services, infrastructure) and **not** sharing a common parent, therefore repeating the same dependencies among them, until here all works fine. Now thinking in work with a common parent, I have consider include Spring IO Platform.

BTW I know how work with parent/child modules in Maven, I did it before, just in this case or situation I am working by first time with Spring IO Platform. I have the following configuration:

**Parent**

<code>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.manuel.jordan.parent</groupId>
	<artifactId>parent-io</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>parent-io-1.0.0</name>

	<properties>
		<maven.test.failure.ignore>true</maven.test.failure.ignore>
		<hikaricp.version>2.3.2</hikaricp.version>
		<jodatime.version>2.7</jodatime.version>
		<junit.version>4.12</junit.version>
		<slf4j.version>1.7.10</slf4j.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			
			<dependency>
            	<groupId>io.spring.platform</groupId>
            	<artifactId>platform-bom</artifactId>
            	<version>1.1.1.RELEASE</version>
            	<type>pom</type>
            	<scope>import</scope>
         	</dependency>
        	
        	<dependency>
    			<groupId>com.zaxxer</groupId>
    			<artifactId>HikariCP</artifactId>
    			<version>${hikaricp.version}</version>
    		</dependency>        	
			<dependency>
    			<groupId>joda-time</groupId>
    			<artifactId>joda-time</artifactId>
    			<version>${jodatime.version}</version>
			</dependency>        	
        	<dependency>
    			<groupId>org.slf4j</groupId>
    			<artifactId>slf4j-api</artifactId>
    			<version>${slf4j.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<modules>
 	         …
		<module>../config/config-datasource-mysql-1.0.0</module>
                 …
	</modules>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build> 
</project>
</code>

**Some Child or Module**

<code>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.manuel.jordan.config</groupId>
	<artifactId>config-datasource-mysql</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>config-datasource-mysql-1.0.0</name>
	<parent>
		<groupId>com.manuel.jordan.parent</groupId>
		<artifactId>parent-io</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../parent/parent-io-1.0.0</relativePath>
	</parent>		
	<dependencies>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
    		<groupId>mysql</groupId>
    		<artifactId>mysql-connector-java</artifactId>
		</dependency>
		<dependency>
    		<groupId>com.zaxxer</groupId>
    		<artifactId>HikariCP</artifactId>
    	</dependency>
	</dependencies>
</code>

I am using the same dependencies versions used when I have worked *with* and *without* **parent/module** approach, that's why I am overriding some dependencies about their versions.

Well, I can compile (prior **Maven-> Update Project** for all the modules - parent and modules), *clean* and *Build All*

When I execute the app I always get:

    13:20:32.445 [main] INFO  com.manuel.jordan.main.Main - Ready....
    Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	    at org.springframework.context.support.AbstractApplicationContext.<init>(AbstractApplicationContext.java:154)
        at org.springframework.context.support.GenericApplicationContext.<init>(GenericApplicationContext.java:100)
	   at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:60)
	    at com.manuel.jordan.main.Main.main(Main.java:18)
    Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	    ... 4 more

Java source code has not been changed, only the pom.xml files to create/update parent/modules relation.

**Note**: If I comment the dependencies overridden I get the same error message.

So, I don't know why that error appears.

More information:

- I've closed the IDE and deleted all the maven repository (I create a dedicated repository for each STS installation, such as sts-workspace-laboratorio) reopen the IDE and all downloaded again and same error

- I've installed a new STS instance with a dedicated repository and I have created a sample project named **spring-io** of the kind **Simple Spring Utility Project** with the following data:

<code>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.manuel.jordan</groupId>
	<artifactId>spring-io</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>spring-io</name>
	<url></url>
	<description>
		<![CDATA[
      This project is a minimal jar utility with Spring configuration.
    ]]>
	</description>
	<properties>
		<maven.test.failure.ignore>true</maven.test.failure.ignore>
		<junit.version>4.12</junit.version>
	</properties>	
	
	<dependencyManagement>
    	<dependencies>
        	<dependency>
            	<groupId>io.spring.platform</groupId>
            	<artifactId>platform-bom</artifactId>
            	<version>1.1.1.RELEASE</version>
            	<type>pom</type>
            	<scope>import</scope>
        	</dependency>
        	<dependency>
 	        	<groupId>junit</groupId>
    	    	<artifactId>junit</artifactId>
    	    	<version>${junit.version}</version>
    	</dependency>
        	
    	</dependencies>
	</dependencyManagement>
	
	<dependencies>
    	<dependency>
 	       <groupId>org.springframework</groupId>
    	    <artifactId>spring-context</artifactId>
    	</dependency>
    	<dependency>
 	       <groupId>org.springframework</groupId>
    	    <artifactId>spring-test</artifactId>
    	</dependency>
    	<dependency>
 	        <groupId>org.springframework</groupId>
    	    <artifactId>spring-orm</artifactId>
    	</dependency>
    	<dependency>
 	        <groupId>junit</groupId>
    	    <artifactId>junit</artifactId>
    	</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
 		</plugins>
	</build> 

</code>

Just when I execute the Testing, for the **ExampleConfigurationTests** class it fails and throws:

```
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<clinit>(SpringJUnit4ClassRunner.java:86)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

**Comment by wilkinsona** [comment]
It looks to me like something is excluding Commons Logging, I would guess in the expectation that SLF4J's commons logging artifact will be used instead. The Platform itself only provides versions in its dependency management, it doesn't configure _any_ exclusions. One possibility is that this dependency management has changed the version of one of your dependencies so that it's now excluding commons logging, where previously it did not.

Can you comment with the effective pom (`mvn help:effective-pom') for one of the problematic projects in both its working and failing configurations?

**Comment by manueljordan** [comment]
I though the same for the first project since I have worked with SLf4J and Logback, but in the same project removing the **platform-bom** artifcatId and using manually each dependency in the same parent (<packaging>pom</packaging>) pom.xml file (all works fine)

To keep the things simple, in the other STS with its own repository and own workspace directory, I've created a simple project named **spring-io** of the kind **Simple Spring Utility Project**, that's the unique project created for that workspace. 

**Note:** SLf4J and Logback are *not* used.

With the generated java code, the test class fails how I posted above. 

Well again the same pom.xml configuration

<code>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.manuel.jordan</groupId>
	<artifactId>spring-io</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>spring-io</name>
	<url></url>
	<description>
		<![CDATA[
      This project is a minimal jar utility with Spring configuration.
    ]]>
	</description>
	<properties>
		<maven.test.failure.ignore>true</maven.test.failure.ignore>
		<junit.version>4.12</junit.version>
	</properties>	
	
	<dependencyManagement>
    	<dependencies>
        	<dependency>
            	<groupId>io.spring.platform</groupId>
            	<artifactId>platform-bom</artifactId>
            	<version>1.1.1.RELEASE</version>
            	<type>pom</type>
            	<scope>import</scope>
        	</dependency>
        	<dependency>
 	        	<groupId>junit</groupId>
    	    	<artifactId>junit</artifactId>
    	    	<version>${junit.version}</version>
    	</dependency>
        	
    	</dependencies>
	</dependencyManagement>
	
	<dependencies>
    	<dependency>
 	       <groupId>org.springframework</groupId>
    	    <artifactId>spring-context</artifactId>
    	</dependency>
    	<dependency>
 	       <groupId>org.springframework</groupId>
    	    <artifactId>spring-test</artifactId>
    	</dependency>
    	<dependency>
 	        <groupId>org.springframework</groupId>
    	    <artifactId>spring-orm</artifactId>
    	</dependency>
    	<dependency>
 	        <groupId>junit</groupId>
    	    <artifactId>junit</artifactId>
    	</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
 		</plugins>
	</build> 
</project>

</code>

Attaching the **Dependency Hierarchy**

![screen shot 2015-02-16 at 5 24 01 pm](https://cloud.githubusercontent.com/assets/2552795/6220185/352e74da-b601-11e4-853c-46828e5f07e7.png)

With the same STS and using the **Effective POM** tab. The results are huge (very long)
Can I attach in somewhere the content?

Thank You.

**Comment by manueljordan** [comment]
Not sure, but since the Spring Projects create the **log4j.properties** files
with the following content

<code>

log4j.rootCategory=INFO, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{ABSOLUTE} %5p %40.40c:%4L - %m%n

</code>

would be that *org.apache.log4j* packages be calling internally in some way the
org/apache/commons/logging/LogFactory?

**Comment by wilkinsona** [comment]
The Platform is inheriting the exclusion of `commons-logging` from `spring-boot-starter-parent`. If you want to use `commons-logging` then you should add an explicit dependency on it or, preferably, use SLF4J's Commons Logging adapter (org.slf4j:jcl-over-slf4j) and an appropriate binding (Logback, for example).

**Comment by manueljordan** [comment]
I don't want use *commons-logging*, I just want use *SLF4J* with *Logback*. 

For many tutorials on the web it only indicate use just 

<code>

        	<dependency>
    			<groupId>org.slf4j</groupId>
    			<artifactId>slf4j-api</artifactId>
    			<version>${slf4j.version}</version>
	        </dependency>
	        <dependency>
    			<groupId>ch.qos.logback</groupId>
    			<artifactId>logback-classic</artifactId>
				<version>${logback.version}</version>
			</dependency>

</code>

**Note**: For the project (**Simple Spring Utility Project**), the default Java code generated by the template has **no** code using logging. 

**Observation**: In the project created, I've **deleted** the unique *log4j.properties* file. Created by default too.

Again I have executed the Project through its testing, the same error appears.

If you said: 

- The Platform is **inheriting the exclusion** of commons-logging from spring-boot-starter-parent

**Question**: Who is using or calling that *commons-logging* if it has been already excluded?.

Your suggestion is the solution: 
Therefore now working with:

<code>

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.manuel.jordan</groupId>
	<artifactId>spring-io</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>spring-io</name>
	<url></url>
	<description>
		<![CDATA[
      This project is a minimal jar utility with Spring configuration.
    ]]>
	</description>
	<properties>
		<maven.test.failure.ignore>true</maven.test.failure.ignore>
		<junit.version>4.12</junit.version>
		<logback.version>1.1.2</logback.version>
		<slf4j.version>1.7.10</slf4j.version>
	</properties>	
	
	<dependencyManagement>
    	<dependencies>
        	<dependency>
            	<groupId>io.spring.platform</groupId>
            	<artifactId>platform-bom</artifactId>
            	<version>1.1.1.RELEASE</version>
            	<type>pom</type>
            	<scope>import</scope>
        	</dependency>
        	<dependency>
 	        	<groupId>junit</groupId>
    	    	<artifactId>junit</artifactId>
    	    	<version>${junit.version}</version>
    		</dependency>
			<dependency>
    			<groupId>org.slf4j</groupId>
    			<artifactId>slf4j-api</artifactId>
    			<version>${slf4j.version}</version>
			</dependency>    		
     		<dependency>
    			<groupId>org.slf4j</groupId>
    			<artifactId>jcl-over-slf4j</artifactId>
    			<version>${slf4j.version}</version>
    		</dependency>
    		<dependency>
    			<groupId>ch.qos.logback</groupId>
    			<artifactId>logback-classic</artifactId>
				<version>${logback.version}</version>
			</dependency>
   	
    	</dependencies>
	</dependencyManagement>
	
	<dependencies>
    	<dependency>
 	       <groupId>org.springframework</groupId>
    	    <artifactId>spring-context</artifactId>
    	</dependency>
    	<dependency>
 	       <groupId>org.springframework</groupId>
    	    <artifactId>spring-test</artifactId>
    	</dependency>
    	<dependency>
 	        <groupId>org.springframework</groupId>
    	    <artifactId>spring-orm</artifactId>
    	</dependency>
    	<dependency>
 	        <groupId>junit</groupId>
    	    <artifactId>junit</artifactId>
    	</dependency>
    	<dependency>
    		<groupId>org.slf4j</groupId>
    		<artifactId>slf4j-api</artifactId>
		</dependency>    		
     	<dependency>
    		<groupId>org.slf4j</groupId>
    		<artifactId>jcl-over-slf4j</artifactId>
    	</dependency>
    	<dependency>
    		<groupId>ch.qos.logback</groupId>
    		<artifactId>logback-classic</artifactId>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
 		</plugins>
	</build> 
</project>

</code>

All work fine… (I've included a logback.xml file too)

**Suggestion**:
This observation could be included in the reference documentation?. We can see that creating a simple project and without explicit logging support fails. Other developer would be confused too.

Thank you very much by your support.

**Comment by wilkinsona** [comment]
That's a fair point about including something in the reference documentation.
