### ISSUE TITLE
Undertow requires Servlet API 3.1

### ISSUE THREAD

**Issue by chrylis** [spring-io/platform#167]
The current CI version of 1.2.2 includes a dependency for Servlet API 3.0.1, but Undertow 1.1.1 (as pulled in by `spring-boot-starter-undertow:1.2.1`) requires `javax.servlet.http.HttpSessionIdListener` from 3.1.

**Comment by wilkinsona** [comment]
We've got little room to maneouver here. Boot 1.2 moved to Servlet 3.1 (Tomcat 8 and Jetty 9) but, for backwards compatibility, the Platform stayed on Servlet 3.0 (Tomcat 7 and Jetty 8). Ideally, the Platform wouldn't include Undertow but it inherits it from Spring Boot. If you want to use Servlet 3.1 with Platform 1.1, you should override `servlet-api.version` (and `tomcat.version` or `jetty.version`, if appropriate)

**Comment by chrylis** [comment]
That's what I'm doing; I just expected swapping `starter-tomcat` for `starter-undertow` to work; instead I get `ClassNotFoundException`.

**Comment by wilkinsona** [comment]
Your expectation's reasonable, unfortunately we're stuck with the way things are until Plaform 2.0 (due this summer) which will move to Servlet 3.1.

**Comment by cforce** [comment]
i stumbled over this secret after half a day.. there is really only this hit on google which was my rescure..
