### ISSUE TITLE
Upgrade to Spring Plugin 1.2.0

### ISSUE THREAD

**Issue by olivergierke** [spring-io/platform#169]
I've just released Spring Plugin 1.2.0 without any real changes but an upgrade from Spring 3.2.8 (yawn) to Spring 4.0.9.

**Comment by wilkinsona** [comment]
Thanks, @Ollie. This version's managed by Boot these days (due to the Spring HATEOAS starter). I've opened https://github.com/spring-projects/spring-boot/issues/2605.
