### ISSUE TITLE
Add io.projectreactor:reactor-core:2.0.0.RELEASE dependency

### ISSUE THREAD

**Issue by artembilan** [spring-io/platform#174]
Actually it would be better to do that in Spring Boot 1.3: upgrade Reactor to 2.0.
Spring Integration is already based on that, by the way.

Thanks

**Comment by wilkinsona** [comment]
As you've noted, Boot provides the version of Reactor. Please raise a Boot issue if you're keen for the version to be updated sooner rather than later.
