### ISSUE TITLE
Upgrade com.jayway.jsonpath:json-path to 2.0.0

### ISSUE THREAD

**Issue by artembilan** [spring-io/platform#175]

**Comment by wilkinsona** [comment]
Boot provides the version of json-path. Please raise a Boot issue if you're keen for the version to be updated sooner rather than later and we can figure out whether or not it'll work (does Spring Framework support 2.0, for example?)

**Comment by artembilan** [comment]
Spring Framework is based on the:
```
optional("com.jayway.jsonpath:json-path:1.2.0")
```
I've just upgraded SI to `2.0.0` from `1.2.0` without issues.

If Boot provides that, then yes: I go ahead with an issue for it.

Thank you!
