### ISSUE TITLE
Include spring-security-test

### ISSUE THREAD

**Issue by paranoiabla** [spring-io/platform#190]
Hi there,
is it possible to have the bom manage the version of the spring-security-test:
http://repo1.maven.org/maven2/org/springframework/security/spring-security-test/4.0.0.RELEASE/

**Comment by wilkinsona** [comment]
`spring-security-test` is new in Spring Security 4.0 so the Platform will include it once it includes the rest of Spring Security 4.0. That'll happen as part of the upgrade to Boot 1.3.0 (#173) which will use Spring Security 4.0 (spring-projects/spring-boot#2727).
