### ISSUE TITLE
Jetty 8.1.16.v20140903 JSP compiling fails on Oracle JDK 8u40

### ISSUE THREAD

**Issue by constap** [spring-io/platform#191]
I've encountered problem with Jetty as an embedded JSP engine: https://bugs.eclipse.org/bugs/show_bug.cgi?format=multiple&id=443594. No idea if this fix will be incorporated into 8.x branch. As a workaround seems to work (not sure, but at least no CharSequence error) by overriding jetty-jsp's org.eclipse.jdt.core dependency version to 3.8.2.v20130121.

**Comment by wilkinsona** [comment]
I'm not sure that there's much we can do about this. In addition to the JSP compilation problems, there are a number of other areas where Jetty 8 doesn't, by default, play nicely with Java 8. For example, `jetty-annotations` depends on an old version of ASM that doesn't understand Java 8 bytecode.

If you want to use Jetty 8 then you will have fewer hoops to jump through if you use Java 7. If you want to use Java 8 then I'd recommend using Jetty 9. You can do so by overriding the `jetty.version` property.

**Comment by constap** [comment]
I see. But why then the platform includes this dependency? Shouldn't it be kind of guaranteed to run on JRE 8?

**Comment by wilkinsona** [comment]
Jetty is included in the Platform as it's an optional dependency of one or more of the Platform's Spring projects. We guarantee that those projects will run on JRE 8, but we do not make the same promise for third-party dependencies as it's largely out of our control.
