### ISSUE TITLE
Spring IO 1.1.2: spring-retry does not use plattform-bom

### ISSUE THREAD

**Issue by RobWin** [spring-io/platform#194]
Hello,

in Spring IO platform v1.1.2 `spring-retry v1.1.2` uses an old spring-core version. It uses spring-core `4.0.4.RELEASE` instead of the `4.1.6.RELEASE`.

spring-retry does not use plattform-bom, but the spring-framework-bom.

Kind regards,
Robert

**Comment by wilkinsona** [comment]
A project that's part of the Platform can't use the Platform's bom as it will create a circular dependency. Instead, your build Maven or Gradle build should import the Platform's bom. This will override `spring-retry`'s default `spring-core` dependency and ensure that it uses the version specified by the Platform instead.

**Comment by RobWin** [comment]
ok. thx
