### ISSUE TITLE
Provide a Link to the Platform Overview

### ISSUE THREAD

**Issue by lazaridis-com** [spring-io/platform#197]
I visited http://spring.io/ and reached at some point this documentation 

http://spring.io/platform/

which describes the Sping Plaform **product**.

Not exactly sure here, but I think there should be a link "Platform" or "Overview" prior to the "Docs" link in the main menu of http://spring.io/

The **project** docu (http://platform.spring.io/platform/) should possibly contain a link to http://spring.io/platform/, too.

**Comment by wilkinsona** [comment]
I'm happy with the links that we currently have on the Platform's project page (http://platform.spring.io/platform). 

I'm also happy with the main menu on http://spring.io site, but that isn't managed in this repository. Please [open a Sagan issue](https://github.com/spring-io/sagan/issues) if you feel strongly about it.

**Comment by lazaridis-com** [comment]
But the very central page http://spring.io/platform/ is lost. I did **not** reach it from the platform's project page (and I would have been happy to have it reached from there). I don't even remember from where I reached it.

In any way, thank you for the friendly pointer to the other repo: spring-io/sagan#536
