### ISSUE TITLE
Spring Boot vs. Platform, Dependence & Relation

### ISSUE THREAD

**Issue by lazaridis-com** [spring-io/platform#201]
from #195 
> `findDuplicates.groovy` - Identifies dependencies that are declared in Spring Boot and in the Platform and that, therefore, should be removed from the Platform

If someone uses the spring-platform, without(!) spring-boot, wouldn't those removed versions be missing?

**Comment by lazaridis-com** [comment]
(possibly related: #170)

**Comment by wilkinsona** [comment]
No. The Platform uses Spring Boot's `spring-boot-starter-parent` bom as its parent so it contains a superset of Spring Boot's dependency management. The `findDuplicates.groovy` script is simply used to avoid unnecessary duplication in the Platform's bom.

**Comment by lazaridis-com** [comment]
(possibly related: #10)
