### ISSUE TITLE
Rationale for Having Spring-Boot as Platform Parent

### ISSUE THREAD

**Issue by lazaridis-com** [spring-io/platform#202]
Within #201 
>The Platform uses Spring Boot's spring-boot-starter-parent bom as its parent so it contains a superset of Spring Boot's dependency management.

Shouldn't `spring-platform` be the top-level pom, without any previous pom from which it inherits?

Or differently: shouldn't `spring-platform` simply import the spring-boot parent (possibly whilst moving it out to an intermediate pom, like e.g. 'spring-boot-platform' or 'spring-boot-bom')?

I'm just wondering, and would like to understand the rationales.

**Comment by wilkinsona** [comment]
`platform-bom` uses `spring-boot-starter-parent` as its parent as that's the easiest (and only) way for it to provide a superset of Spring Boot's dependency management while also inheriting its default Maven plugin configuration.

**Comment by lazaridis-com** [comment]
@wilkinsona , please note that your rationale is invalid.

(Additionally, you should not close issues that fast, usually the person who files an issue decides when it is solved / closed).
