### ISSUE TITLE
Add Spring Security Kerberos

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/platform#205]

**Comment by wilkinsona** [comment]
This is blocked by Spring LDAP's dependency on Apache DS 1.5.5 and Spring Security Kerberos' dependency on Apache DS 2.0

**Comment by jvalkeal** [comment]
True sec kerberos rely on 2.0.0-M15 which is soon already 2 years old. Actual implementation what we use to do testing(not just test because dep is coming from spring-security-kerberos-test package) is based on code made for hadoop and afaik it doesn't work below M15.

Thinking that DS 1.5.5 is from Aug 2009, maybe we should pump up Spring LDAP?

**Comment by wilkinsona** [comment]
That's my preference, but, the last I heard, @rwinch was reluctant to move to 2.0.

**Comment by rwinch** [comment]
@wilkinsona I'd be ok with looking into supporting both versions. My hesitation is that ApacheDS has been in milestone for quite some time (and as far as I remember changed quite a bit between milestones).

**Comment by wilkinsona** [comment]
@rwinch Thanks. FWIW, they have M21 listed in [JIRA](https://issues.apache.org/jira/browse/DIRSERVER/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel) then a couple of RCs. No dates though, unfortunately. Perhaps we could just pick a milestone and see what it would take to support it in Spring Security, Spring LDAP, and Spring Security Kerberos?

**Comment by rwinch** [comment]
I'm ok with that. If we did that I'd like to pick M20 since it is the latest release. Thoughts?

**Comment by wilkinsona** [comment]
Makes sense to me. Going with the latest should, hopefully, give us the least amount of work to do if/when we jump to the 2.0 GA

**Comment by rwinch** [comment]
@wilkinsona What version of Security would need this (i.e. just 4.0.x or would 3.2.x need to also support this new version of ApacheDS)? I created [SEC-3024](https://jira.spring.io/browse/SEC-3024) and updated [LDAP-320](https://jira.spring.io/browse/LDAP-320)

**Comment by wilkinsona** [comment]
@rwinch Just 4.0

**Comment by rwinch** [comment]
@wilkinsona Thanks for the reply. I have tried to get an embedded ApacheDS LDAP instance setup, but have struggled finding a working example. As far as I can tell the [documentation](https://directory.apache.org/apacheds/advanced-ug/7-embedding-apacheds.html) and [tests](https://github.com/apache/directory-server/blob/75ba349c8654a96e2213e6f9c6ab9eb4ba00c07f/server-jndi/src/test/java/org/apache/directory/server/configuration/ApacheDSTest.java#L45) leave this as a TBD. I still have the issue open, but unless I get a PR I don't think this will make Spring Security 4.0.2.
