### ISSUE TITLE
xml-apis:xml-apis version

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-io/platform#209]
In 2.0.0.BUILD-SNAPSHOT, xml-apis:xml-apis version is 1.3.04. But latest version of xml-apis:xml-apis is 1.4.01. 
Why depend on the 1.3.04(old version) ?
If possible, i hope upgrade to 1.4.01(latest version).

**Comment by bclozel** [comment]
I think this dependency is [managed by Boot](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-dependencies/pom.xml).

**Comment by kazuki43zoo** [comment]
@bclozel 

Thank you for your comment.
xml-apis has been managed by [this commit](https://github.com/spring-projects/spring-boot/commit/e6dfd7c5336e20e737e6724784c739348bae9094#diff-083b496f7d7090ebebfb261636fbe139) ...

**Comment by wilkinsona** [comment]
Thanks, @bclozel.

@kazuki43zoo The commit in Spring Boot that you've pointed to is a temporary workaround that should be reverted before Spring Boot 1.3 and Spring IO Platform 2.0 are released. See https://github.com/spring-projects/spring-boot/issues/2884 for more details. We could, perhaps, upgrade to 1.4.01 in the meantime, but that change would have to be made in Spring Boot, not in the Platform.

**Comment by kazuki43zoo** [comment]
@wilkinsona 

Thanks or your comment.
I was understood your comment.
I wait until reverting a temporary workaround of Spring IO Platform 2.0 (Spring Boot 1.3).
