### ISSUE TITLE
Add Spring Statemachine

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/platform#214]

**Comment by jvalkeal** [comment]
All right, spring statemachine 1.0.0.RELEASE is out in repos.

**Comment by jvalkeal** [comment]
paging @wilkinsona statemachine 1.0.1.RELEASE is in central

**Comment by wilkinsona** [comment]
The dependency on Spring Cloud, specifically `org.springframework.cloud:spring-cloud-cluster-zookeeper` means that Spring Statemachine cannot be added to the Platform. The Platform does not include Spring Cloud and we have no plans to change that.
