### ISSUE TITLE
No com.googlecode.gson:gson in actual pom

### ISSUE THREAD

**Issue by cmousset** [spring-io/platform#224]
The reference mentions:
com.google.code.gson gson 2.3.1

However, I did not find gson in the actual pom. I searched 1.1.2 RELEASE and above.
Could it be added?

**Comment by wilkinsona** [comment]
It's already there. You didn't see it in the platform-bom pom as it's inherited from Spring Boot.

**Comment by cmousset** [comment]
Thanks. I apologize for not seeing it.

Op za 4 jul. 2015 13:53 schreef Andy Wilkinson <notifications@github.com>:
