### ISSUE TITLE
Please include the Spring Cloud release train into the spring.io platform

### ISSUE THREAD

**Issue by joshuawhite929** [spring-io/platform#232]
Please include the Spring Cloud release train into the spring.io platform (Similar to the Spring Data release train).

See: http://stackoverflow.com/questions/31924017/a-spring-cloud-releasetrain-like-spring-data

**Comment by dsyer** [comment]
This will probably not happen (or at least not yet) because Spring Cloud is kind of a higher level in the stack. It doesn't explicitly depend on Spring IO, but in principle it could.

Note that you can use the Spring Cloud release BOMs to augment dependencies from the platform. It's only one extra dependency.

**Comment by wilkinsona** [comment]
Spring Cloud's a different beast to Spring Data and, as such, we don't have any plans to include it in the Platform.

The Platform's primary goal is intended to make it easy to write applications that using the various Spring projects. There are number of Spring Cloud's dependencies that an application developer shouldn't care about. For example, the version of Spring Cloud's config server should be of no concern. As such, it doesn't make sense to include Spring Cloud in the Platform.

The above said, we'll still do what we can to keep everything working nicely together. If you encounter problems like https://github.com/spring-cloud/spring-cloud-netflix/issues/484, please let us know.

**Comment by joshuawhite929** [comment]
I get that cloud is a different beast.  This becomes frustrating when a company leverages a given version of the platform and cloud depends on yet another version which causes a conflict.  We had this problem already (Netflix dependencies) The platform was meant to solve that very issue.

This works differently than I thought.  This means cloud will drive the version of platform an org should be using then, not the other way around.  This is the only project that works this way.

**Comment by dsyer** [comment]
We know. But Spring Cloud a) depends on Spring Boot for its own dependency management, and b) has dependencies that are not necessarily going to work with arbitrary combinations of stuff in the platform (e.g. jersey 1.x).

We don't want to change a), but that doesn't necessarily mean in principle that cloud stuff can't be in the platform at some stage. But b) is more of an issue: we actively do not want to drag stuff into the platform transitive my that is not "generally" useful for spring boot apps.
