### ISSUE TITLE
Upgrade commons-lang3 to 3.4

### ISSUE THREAD

**Issue by NickManley** [spring-io/platform#271]
Not sure if it's too late for this to make it into the 2.0 release, but version 3.4 of commons-lang3 fixes an important bug for me. It doesn't look like it would cause any major issues. From the release notes...

"Commons Lang 3.4 is fully binary compatible to the last release and can therefore be used as a drop in replacement for 3.3.2"

https://commons.apache.org/proper/commons-lang/release-notes/RELEASE-NOTES-3.4.txt

**Comment by wilkinsona** [comment]
I'd prefer not to make this change post RC. You can use 3.4 by overriding the `commons-lang3.version` property. Please see the [reference guide](http://docs.spring.io/platform/docs/current/reference/htmlsingle/#getting-started-overriding-versions) for more information on overriding the Platform's dependency management.
