### ISSUE TITLE
Upgrade to Spring Security OAuth 2.0.8.RELEASE

### ISSUE THREAD

**Issue by ractive** [spring-io/platform#272]
spring-security-oauth has been upgraded to 2.0.8.

**Comment by julien-may** [comment]
+1

**Comment by wilkinsona** [comment]
The version of Spring Security OAuth is a managed by Spring Boot so this'll happen naturally as part of upgrading Spring Boot's version.

**Comment by wilkinsona** [comment]
Now I remember that's only the case in Boot 1.3/Platform 2.0
