### ISSUE TITLE
Upgrade lombok to 1.16.x

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-io/platform#275]
Lombok 1.16.x has been released by this year.
In 1.16.x, some external features has been adopted into core feature (e.g. `@Builder`, etc ...).
In addition, spring-hateoas already depends on [1.16.4 as provided scope](https://github.com/spring-projects/spring-hateoas/blob/master/pom.xml#L471-L476). 

@wilkinsona , do you have an update plan ?

**Comment by wilkinsona** [comment]
The version of Lombok used by Spring HATEOAS doesn't matter. Lombok's only involved at compile time, hence its use of the provided scope.

**Comment by kazuki43zoo** [comment]
Thank you for quick answer

> The version of Lombok used by Spring HATEOAS doesn't matter. Lombok's only involved at compile time, hence its use of the provided scope.

OK. i understand it. (Incidentally, i commented referring #40 about Spring HATEOAS)
Thanks.
