### ISSUE TITLE
Maven Filter Stops Working with Spring BOM 2.0.0

### ISSUE THREAD

**Issue by billparkinson** [spring-io/platform#277]
I changed my parent from Spring BOM 1.1.4 to 2.0.0.

Now, oddly enough filtering does not work in Maven under Jenkins. (Serious head scratching)

All of my projects have a build.properties file in resources with entries like: 
jenkins_build_id=${env.BUILD_ID}

Maven uses a filter to process this file:

<build>
		<resources>
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/*.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>**/*.properties</exclude>
				</excludes>
			</resource>
		</resources>

Normal result (prior to using Spring BOM 2.0.0 was a build.properties file in target classes with entries like
jenkins_build_id=634

However once I switch to 2.0.0 the substitution does not happen.  The output file has jenkins_build_id=${env.BUILD_ID} instead.

This has me baffled, because I cannot see the link between build source changing (Spring BOM 1.1.4 to 2.0.0) and the maven filter.

I have tried latest and greatest, Jenkins 1.638 and Maven 3.3.9 to no avail.

Using Maven -X I can see that the env.BUILD_ID is being passed to maven using both Spring BOM 1.1.4 and 2.0.0.  I can also see that maven is using the same version of filter plugin and that in both cases maven reports that it filtered the file. (But in the 2.0.0 case the filtering does not happen.)

I am really stumped here.  No matter what artifacts maven builds that should not affect the build process.  There a ton of properties passed to maven filter for various versions, Perhaps there is some property thats getting reinterpreted by filter??

**Comment by wilkinsona** [comment]
The resource filtering isn't set up by the Platform, but by Spring Boot. By upgrading to Platform 2.0.0, you're now using Spring Boot 1.3.0. Its [resource filtering configuration has changed](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering). You'll either need to update the files that are being filtered accordingly, or reconfigure the filtering.

**Comment by billparkinson** [comment]
Andy,

Thanks!!!!

I missed that when I googled for the solution.   Easy fix.

PS Spring BOM is the best!  It keeps me sane!

Thanks Again
Bill Parkinson
