### ISSUE TITLE
please add hazelcast-wm

### ISSUE THREAD

**Issue by jurisz** [spring-io/platform#278]
Please add com.hazelcast:hazelcast-wm
as most of hazelcast jars are already available

**Comment by wilkinsona** [comment]
The Hazelcast dependency management is provided by Spring Boot from where the Platform inherits it. Please [open a Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/new) if you'd like to see an addition to its dependency management for Hazelcast.
