### ISSUE TITLE
Upgrade to guava 19.0

### ISSUE THREAD

**Issue by akiraly** [spring-io/platform#306]
It seems Spring IO is still using 17.0 which is now more than 1.5 years old.

**Comment by wilkinsona** [comment]
Unfortunately, Guava regularly breaks backwards compatibility (hence 3 major versions in the last 1.5 years) and it's quite likely that everything in the Platform will not be compatible with 19.0. We may get to version 19 (or later) at some point, but I can't offer any guarantees about when that will happen, or that it will even happen at all.

Given this uncertainty, I'm going to close this issue. If you want to use Guava 19.0, you can override the Platform's dependency management to use that version.
