### ISSUE TITLE
use slenium.version property

### ISSUE THREAD

**Issue by tsachev** [spring-io/platform#309]
Currently `platform-bom` defines dependency version for
`selenium-htmlunit-driver` with `selenium-htmlunit-driver.version`.

However if my application needs another _selenium_ driver dependency
for integration testing. For example let say I have this

```
<properties>
...
    <selenium.version>2.47.0</selenium.version>
...
</properties>
```
and
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>${selenium.version}</version>
    <scope>test</scope>
</dependency>
```

I need to fix the version from platform bom in order to get the correct version of `selenium-api`.

```
<properties>
...
    <selenium.version>2.47.0</selenium.version>
    <selenium-htmlunit-driver.version>${selenium.version}</selenium-htmlunit-driver.version>
...
</properties>
```

**Comment by wilkinsona** [comment]
It was a deliberate decision to use `selenium-htmlunit-driver.version` as that's the only part of Selenium for which the Platform provides dependency management and I didn't want the name of the property to imply that the Platform provides anything more.

However, looking at the pom for `selenium-htmlunit-driver` that limited dependency management may actually be problematic as `selenium-htmlunit-driver` depends on `org.seleniumhq.selenium:selenium-support`. With no dependency management for the latter, the versions of the two could end up being mismatched.

I think a couple of changes are appropriate here:

 - Add a `selenium.version` property (consider keeping `selenium-htmlunit-driver.version`, for the time being at least, for backwards compatibility)
 - Add dependency management for `org.seleniumhq.selenium:selenium-support`

**Comment by wilkinsona** [comment]
The dependency management for Selenium has moved into Boot in 1.4 so this needs to be tackled there.
