### ISSUE TITLE
Consider adding dependency management for Spring Data JDBC Extensions

### ISSUE THREAD

**Issue by vpavic** [spring-io/platform#310]
There are two modules from this project:

```xml
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-jdbc-core</artifactId>
    <version>1.2.1.RELEASE</version>
</dependency>
```

```xml
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-oracle</artifactId>
    <version>1.2.1.RELEASE</version>
</dependency>
```

Note that ```spring-data-oracle``` module has some dependencies (with ```provided``` scope) that are not available from public repo's, see [here](https://github.com/spring-projects/spring-data-jdbc-ext/tree/master/spring-data-oracle) for details. I don't know if this is an issue from Platform's perspective.

**Comment by wilkinsona** [comment]
> I don't know if this is an issue from Platform's perspective

Unfortunately, it is. Everything in the Platform needs to be resolvable from public Maven repositories.
