### ISSUE TITLE
Upgrade to Spring Boot 1.4.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/platform#311]

**Comment by amezick** [comment]
Will spring platform upgrade the framework to 4.3.0 with boot 1.3.6 or boot 1.4.0?

**Comment by wilkinsona** [comment]
1.4. Boot 1.3.x continues to use Spring Framework 4.2.x

**Comment by tkvangorder** [comment]
Is there a tentative release schedule for 2.1?

**Comment by wilkinsona** [comment]
See https://github.com/spring-io/platform/milestones. It's called Athens now.

**Comment by tkvangorder** [comment]
awesome, thanks!

**Comment by wilkinsona** [comment]
And I've just realised that we're going to have to wait for Boot 1.4.1. The milestones page has been updated accordingly.

**Comment by tkvangorder** [comment]
Oh Right, I remember someone mentioning at SpringOne that they had to use a snapshot build of boot 1.4 due to bug. Thanks for the quick reply.
