### ISSUE TITLE
spring-code-of-conduct@pivotal.io not working

### ISSUE THREAD

**Issue by lazaridis-com** [spring-io/platform#318]
I tried to send an email to `spring-code-of-conduct@pivotal.io`, and got the following autoreply:

Hello info@lazaridis.com,

We're writing to let you know that the group you tried to contact (spring-code-of-conduct) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/pivotal.io/bin/topic.py?topic=25838.

Thanks,

pivotal.io admins

**Comment by wilkinsona** [comment]
Sorry and thanks for letting us know about the problem. We're looking into it and I'll comment again once it's been resolved. In the meantime, if you have an issue that needs to be addressed urgently, you can email me at the same domain by using `awilkinson` in place of `spring-code-of-conduct`.

**Comment by wilkinsona** [comment]
The issue with `spring-code-of-conduct@pivotal.io` has now been resolved. Thanks again for alerting us to the problem.
