### ISSUE TITLE
assertj upgraded to 3.3.0

### ISSUE THREAD

**Issue by linux-china** [spring-io/platform#320]
3.3.0 includes all changes from AssertJ core 2.3.0 and additional ones specific to Java 8.
http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.3.0

**Comment by wilkinsona** [comment]
The version of AssertJ is actually managed by Spring Boot and inherited from there by the Platform. Furthermore, 3.3 requires Java 8 and both Spring Boot and the Platform are required to be Java 7 compatible.
