### ISSUE TITLE
Improve Gradle documentation to describe how to use the Platform with Boot

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/platform#328]

**Comment by RichSteele** [comment]
*Is* there a way to combine Platform with Boot in such a way that you don't have to specify the version of the Boot Gradle plugin?

**Comment by wilkinsona** [comment]
No, there isn't. Unlike Maven, Gradle has no concept of plugin management so there's no way for the Platform to manage the version of Spring Boot's Gradle plugin.
