### ISSUE TITLE
Update to latest Bouncy Castle

### ISSUE THREAD

**Issue by rwinch** [spring-io/platform#329]
Spring Platform uses Bouncy Castle 1.47 which is about 3 years old. We should up to the current version of Bouncy Castle (at the time of this writing it is 1.54)

**Comment by wilkinsona** [comment]
IIRC, I've tried this before and bad things happened. Unfortunately, I can't remember the details. Let's give it another try and see how it goes.

**Comment by bclozel** [comment]
This rings a bell as well.
Right now I'm thinking JRuby (this library is shipped with JRuby, version 1.47) and backwards incompatible changes in Bouncy Castle's API.

**Comment by wilkinsona** [comment]
This looks good from a compatibility perspective. @bclozel @rwinch If you notice any problems, please comment here.
