### ISSUE TITLE
c3p0 duplicate dependency with quartz

### ISSUE THREAD

**Issue by xenoterracide** [spring-io/platform#331]
```
[INFO] +- org.quartz-scheduler:quartz:jar:2.2.2:compile
[INFO] |  \- c3p0:c3p0:jar:0.9.1.1:compile
```
and
```
[INFO] +- com.mchange:c3p0:jar:0.9.5.2:compile
[INFO] |  \- com.mchange:mchange-commons-java:jar:0.2.11:compile
```

*shouldn't quartz use the version provided by the bom?*

here's the relevant parts of our POM, I'm aware that 2.0.3 is out we have not had time to upgrade yet.

```
	<parent>
		<groupId>io.spring.platform</groupId>
		<artifactId>platform-bom</artifactId>
		<version>2.0.2.RELEASE</version>
		<relativePath/>
	</parent>

		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
		</dependency>

		<dependency>
			<groupId>com.mchange</groupId>
			<artifactId>c3p0</artifactId>
		</dependency>
```

**Comment by wilkinsona** [comment]
Ideally, yes. Unfortunately, C3P0's coordinates changed between 0.9.1 and 0.9.2. From Maven's perspective, that means they're entirely different artifacts.

Maven's dependency management doesn't provide a way for the Platform's bom to substitute one artifact for another so it's something that you'll have to deal with manually. Assuming that Quartz is compatible with 0.9.5, your best best is to add an exclusion for `c3p0:c3p0` to your dependency on Quartz.
