### ISSUE TITLE
Get rid of <smack.version>3.2.1</smack.version> dependencies

### ISSUE THREAD

**Issue by artembilan** [spring-io/platform#335]
After upgrading Spring Boot to Spring WS 2.3 (https://github.com/spring-projects/spring-boot/commit/e14329c77bd7ec2a852d66dbe704c56a0587639f), and upcoming upgrade for Spring Integration (https://github.com/spring-projects/spring-integration/pull/1767), no one Spring project is going to use legacy `Smack 3.2` artifacts.

Feel free to remove them altogether from the Platform as well.

**Comment by wilkinsona** [comment]
Thanks, @artembilan. This has already been taken care of in 0fb9b62.
