### ISSUE TITLE
Consider adding dependency management for eclipse-collections

### ISSUE THREAD

**Issue by vpavic** [spring-io/platform#352]
Eclipse Collections is the successor of GS Collections for which the Platform already offers dependency management.

References:
https://www.eclipse.org/collections/
https://github.com/eclipse/eclipse-collections
https://github.com/goldmansachs/gs-collections

**Comment by wilkinsona** [comment]
The Platform's contents are governed by the dependencies of the various Spring projects that it contains. Dependency management for Eclipse Collections will be added if/when a project starts using it but not before.
