### ISSUE TITLE
broken link to boundless repo 

### ISSUE THREAD

**Issue by jodygarnett** [spring-io/platform#357]
This line here https://github.com/spring-io/platform/blob/master/platform-tests/src/test/resources/pom-footer.template#L16

Should reference http://repo.boundlessgeo.com/main ?

**Comment by wilkinsona** [comment]
Thanks. Looks like the URL changed as part of their more to Artifactory. It would appear that the repo is now redundant (it was being used to resolve some transitive dependencies of Neo4J) so I've removed it in https://github.com/spring-io/platform/commit/7627d9e5a25d3989e0049b5925978e4a5cdad05e.
