### ISSUE TITLE
Upgrade to ejb-api 3.2

### ISSUE THREAD

**Issue by apinske** [spring-io/platform#411]
We would like to use `@Startup` and `@Singelton` in our EJBs. Would you consider updating the dependency of ejb-api from 3.0 to 3.1?

**Comment by wilkinsona** [comment]
3.2 is the latest. Moving to that for the next release seems reasonable.

**Comment by snicoll** [comment]
Some note about this. As of `ejb-api` 3.2, the `javax.intereceptor` package has been factored out in its own `interceptor-api` library. Do we have dependency management for that as well? If we don't, we probably should (`javax.interceptor:javax.interceptor-api:1.2`).

**Comment by wilkinsona** [comment]
Thanks, @snicoll. Unless one of the Spring projects in the Platform depends on any `javax.interceptor` classes, I'd prefer to take the opportunity to reduce the surface area a little.

**Comment by wilkinsona** [comment]
The `javax.interceptor` classes are used by Spring Framework so we need to provide dependency management for them.
