### ISSUE TITLE
Consider adding dependency management for Commons JEXL

### ISSUE THREAD

**Issue by vpavic** [spring-io/platform#437]
Hibernate Validator's [`@ScriptAssert` constraint](https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ScriptAssert.html) offers JEXL based script expression validation which requires [Commons JEXL](http://commons.apache.org/proper/commons-jexl/). Since Spring Boot provides dependency management for Hibernate Validator perhaps it would make sense for Platform to provide this optional dependency?

**Comment by wilkinsona** [comment]
Sorry, but to keep the scope manageable, something would need to depend directly on Commons JEXL before we'd add dependency management for it.
