### ISSUE TITLE
Improve documentation about the dependency version upgrade

### ISSUE THREAD

**Issue by chhsiao90** [spring-io/platform#449]
I think it will be nice to have the information about which dependency had new version from previous old version on the documentation.
So that user could know about the impact when they want to upgrade the spring platform version.
Thanks!

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I've thought about that in the past, but couldn't think of a good way to display the information. The problem is that the information varies depending on which version the user is upgrading from. I can't think of anything better than just manually comparing the table of versions that's already in the documentation. If you have a suggestion for something better, please let me know.

**Comment by chhsiao90** [comment]
Yeah, one problem is the upgrading is from which version of spring platform.
My idea is to display the version comparison table between current version and previous release/tag version, for example, current release version is Athens and previous release version is 2.0.8, then display the version comparison between the two version like

Group                          |Artifact       |Previous Version|Current Version
----------------------|-----------|-----------------|----------------
org.springframework|spring-core|2.0.7.RELEASE    |4.3.3.RELEASE


But I found that there maybe is some technical issue about document generation.
Currently, the version table was generated automatically by maven dependency plugin and groovy script. So it's hard to get the dependency from previous release...

I would take some days to think about it! And would close the issue if there is no progress.
Thanks!

**Comment by chhsiao90** [comment]
I think it's hard to append the information in the document.
But maybe it could have a link in the spring platform website that provide functionality to show dependency difference table between spring platform versions.
Just a demo site for reference that I had implement: [spring-io-platform-deps](https://chhsiao90.github.io/spring-io-platform-deps)

**Comment by chhsiao90** [comment]
Maybe it was really hard to display it clearly or have a place to display it.
Just provide an idea which good to have.
I will close the issue and thanks for your feedback and thanks for this project that bring us so much convenience to resolve dependency management problem!
