### ISSUE TITLE
Add MyBatis & MyBatis Spring

### ISSUE THREAD

**Issue by jiafuzhang** [spring-io/platform#461]
Please add MyBatis,MyBatis Spring.
And other MyBatis dependency.
Thank you!
Besides,i discover a link error.
http://spring.io/docs/reference  -> Spring IO Platform -> <Site> Link is wrong.
Please change.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but the Platform only contains the dependencies of the Spring projects that are part of the Platform. None of them depend on MyBatis so MyBatis is not included in the Platform.

Which link do you think is wrong? They all seem fine to me.

**Comment by jiafuzhang** [comment]
Spring IO is a good project.
In the process of using spring IO can ignore rely on the version of the project, reduce a lot of unnecessary trouble, and compatibility issues. Very convenient.
This is a great innovation, I hope he can be more powerful.
If one day, after adding the spring IO, when using other techniques, only need to tell him the name of technology, it is a wonderful thing.
At that time, the developers believe that using spring IO will be more and more.
thank you!
link is ok.
