### ISSUE TITLE
Upgrade to io.projectreactor.ipc:reactor-netty 0.6

### ISSUE THREAD

**Issue by artembilan** [spring-io/platform#466]
Spring Integration 5.0 uses `reactor-netty` for STOMP module, but as `optional` compile dependency. That's why we compile fine , but fail with testing against IO: https://build.spring.io/browse/INT-FATS5IC-7/

**Comment by wilkinsona** [comment]
`reactor-netty` is already there. Looks like we need to update the version.

**Comment by garyrussell** [comment]
gentle nag...

...our nightly 5.0/Cairo compatibility build is failing for this (and I have an aversion to the color red 😄  )

**Comment by wilkinsona** [comment]
Sorry, I made the change on Monday and evidently forgot to push it. I've done so now.

**Comment by garyrussell** [comment]
Thanks Andy.

**Comment by wilkinsona** [comment]
This dependency is now managed in Boot due to its use of Reactor's bom
