### ISSUE TITLE
Athens-SR1 pulls in elasticsearch-2.4.1 which requires guava 18

### ISSUE THREAD

**Issue by conor-roche-rockalltech** [spring-io/platform#467]
platform Athens-SR1 pulls in elasticsearch-2.4.1 (via spring boot dependencies) which requires guava 18, but platform uses guava 17 as a result i get the following error on building the es client

Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at org.elasticsearch.threadpool.ThreadPool.<clinit>(ThreadPool.java:192)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:131)

I could just upgrade to guava 18 but wanted to know if there are known compatability issues with other components in the platform with guava 18?

**Comment by wilkinsona** [comment]
Guava is, unfortunately, a liability. They only ever release new major versions which regularly contain breaking API changes. That makes using it in a library such as the Elasticsearch Client a very risky thing to do.

We've stuck with Guava 17 as, until now, we haven't been aware of any problems with it. I haven't heard of anyone having compatibility issues with Guava 18 so I'd recommend trying it.

We can consider upgrading to Guava 18 in the Brussels release of the platform.

**Comment by wilkinsona** [comment]
I've opened #475 to try to move to Guava 20.0 in Brussels. Unfortunately there's nothing we can do in Athens.

**Comment by conor-roche-rockalltech** [comment]
@wilkinsona note I got it working fine with guava 18 in athens
