### ISSUE TITLE
dependencies removed from platform BOM, but not documented

### ISSUE THREAD

**Issue by xenoterracide** [spring-io/platform#469]
`commons-configuration`, `tomcat-embed-logging-juli` were removed in Athens. I'm ok with this removal (we are currently removing it). It is not listed in the removed section and should be.

http://docs.spring.io/platform/docs/current/reference/htmlsingle/#upgrading-dependency-management-removed

**Comment by xenoterracide** [comment]
was going to try to write this patch in my free time but I can't find the code that maintains this (at last not just on github)

**Comment by wilkinsona** [comment]
Thanks for the offer. I've just taken care of this in https://github.com/spring-io/platform/commit/267f81013d649ccf1bf044b362849832b2888647. For future reference, you can find the source for the documentation [here](https://github.com/spring-io/platform/tree/athens/platform/src/main/asciidoc). The table in question is in [upgrading.adoc](https://github.com/spring-io/platform/tree/athens/platform/src/main/asciidoc/upgrading.adoc).

**Comment by izeye** [comment]
@wilkinsona Resolved?

**Comment by wilkinsona** [comment]
@izeye Not sure why GitHub didn't auto-close it as it picked up the commit OK. Thanks for the catch.
