### ISSUE TITLE
more constistent platform naming

### ISSUE THREAD

**Issue by xenoterracide** [spring-io/platform#471]
Although I really fundamentally dislike the "alphabetic" naming, and would have preferred to using a more meaningless "year"  (car release style) like 2017.0 2017.1, I'll get over it.

However, I'm wondering if the next release instead of having Brussels-RELEASE, Brussels-SR1 could we maybe do Brussels-SR0, Brussels-SR1? so it it at least easier to guess and tell someone to upgrade to the next version without having to tell them what that is?

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but the Platform's following the convention established by Spring Data and Spring Cloud. We don't want to introduce another one.
