### ISSUE TITLE
upgrade tomcat to 8.5.9 or greater

### ISSUE THREAD

**Issue by xenoterracide** [spring-io/platform#485]
I now regret not making this issue before the release because I thought it would get bumped as part of the release process.

we're hitting this issue in 8.5.6 it was fixed in 8.5.7, 8.5.9 is the latest as of this writing

> Fix:  Exclude JAR files in /WEB-INF/lib from the static resource cache. (markt)

https://tomcat.apache.org/tomcat-8.5-doc/changelog.html#Tomcat_8.5.7_(markt)

**Comment by wilkinsona** [comment]
The version of Tomcat is managed by Boot. We can't upgrade to 8.5.9 as it contains a regression. See https://github.com/spring-projects/spring-boot/issues/7360 for details

**Comment by xenoterracide** [comment]
I would like to say that I find it impossible to determine whether a dependency is managed by boot, platform, or one of the other meta bom's (e.g. data). so it is difficult without source diving to know which project to report a bug to, and frustrating (probably on both sides) to be told be told project x manages that... I don't know if perhaps there's some way to improve the documentation (in an automated way) regarding which dependencies are managed where.

**Comment by bclozel** [comment]
Spring Boot provides the complete list of managed dependencies in [its reference documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html).
