### ISSUE TITLE
Add Nimbus OAuth 2.0 and JOSE+JWT SDK

### ISSUE THREAD

**Issue by jgrandja** [spring-io/platform#489]
@wilkinsona Would it be possible to add [Nimbus OAuth 2.0 + OpenID Connect](http://connect2id.com/products/nimbus-oauth-openid-connect-sdk) AND [Nimbus JOSE + JWT](http://connect2id.com/products/nimbus-jose-jwt) to the Spring IO Cairo release?

@rwinch and I are leveraging Nimbus for the new OAuth2 Client which is targeted for Spring Security 5.0.0.M1 release.

**Comment by wilkinsona** [comment]
It would indeed

**Comment by wilkinsona** [comment]
@jgrandja @rwinch What are the Maven coordinates of the artifacts? I think it's these:

 - http://central.maven.org/maven2/com/nimbusds/oauth2-oidc-sdk/5.9.1/
 - http://central.maven.org/maven2/com/nimbusds/nimbus-jose-jwt/4.34.1/

Can you please confirm or correct as appropriate?

**Comment by jgrandja** [comment]
Excellent thanks @wilkinsona !

**Comment by jgrandja** [comment]
@wilkinsona Looking at 

- http://central.maven.org/maven2/com/nimbusds/oauth2-oidc-sdk/maven-metadata.xml

the latest release is **5.21**

- http://central.maven.org/maven2/com/nimbusds/oauth2-oidc-sdk/5.21/

so let's go with that.

JOSE+JWT is the correct version. Latest is 4.34.1 based on:

- http://central.maven.org/maven2/com/nimbusds/nimbus-jose-jwt/maven-metadata.xml

**Comment by wilkinsona** [comment]
Thanks, @jgrandja. Alphabetical sorting of numeric values trips me up once again

**Comment by wilkinsona** [comment]
@jgrandja @rwinch Both dependencies are now in Cairo snapshots. Please let me know when there's a Spring Security snapshot available that's using them.

**Comment by jgrandja** [comment]
Thanks @wilkinsona! We should have a snapshot using Nimbus dependencies sometime late Feb or early March. Will definitely let you know when it's in.
