### ISSUE TITLE
Jackson-Annotations version?

### ISSUE THREAD

**Issue by madorb** [spring-io/platform#519]
Not necessarily an issue, but just curious why the version of  `jackson-annotations` is `2.8.0` while the rest of the jackson suite is `2.8.6`?

**Comment by madorb** [comment]
Nm, it looks like it's because that's what jackson is doing, i assume because the annotations really should not ever change from within a minor release

**Comment by mjustin** [comment]
Here's the relevant Jackson issue regarding this — https://github.com/FasterXML/jackson-databind/issues/1510.  The short version: all the 2.8.x versions of jackson-annotations are the same, so it doesn't matter if you're using 2.8.0 or 2.8.6.
