### ISSUE TITLE
spring-data-redis with lettuce broken in Brussels-RELEASE

### ISSUE THREAD

**Issue by sjulean-elan** [spring-io/platform#522]
`platform-bom:Brussels-RELEASE` comes with `spring-data-redis:1.8.0.RELEASE` and `lettuce:3.5.0.Final`.

However, `spring-data-redis:1.8.0.RELEASE` requires (and is compiled against) `lettuce:4.2.2.Final`.

See: http://docs.spring.io/spring-data/redis/docs/1.8.0.RELEASE/reference/html/#new-in-1.8.0

See also: https://github.com/spring-projects/spring-data-redis/blob/76991fb12cbc519490951b94cc191833cf9f87b0/pom.xml
(This commit appears to correspond to `1.8.0.RELEASE`, but the release is untagged in git.)

As a workaround, it is possible to override the lettuce version or use another redis client.

I wonder if such an issue could be caught by tests in the case of optional dependencies.

**Comment by wilkinsona** [comment]
Thanks for reporting this.

> I wonder if such an issue could be caught by tests in the case of optional dependencies.

It can (and should have been). I've opened #523 to test that we're not inadvertently downgrading a dependency.
