### ISSUE TITLE
Upgrade to Spock 1.1

### ISSUE THREAD

**Issue by lievendoclo** [spring-io/platform#573]
Currently the version in the platform is 1.0, which has issues when using it with spock-spring and Spring Boot testing. Version 1.1 solves these issues.

**Comment by lievendoclo** [comment]
While the dependency isn't in the POM afaik, Gradle's dependency management plugin does find it and reports as 1.0. Perhaps it needs to be added to the BOM.

**Comment by wilkinsona** [comment]
The dependency management is in Spring Boot. It can't be upgraded until 1.1 moves out of the RC phase.
