### ISSUE TITLE
Please add the spring-cloud-dependencies and pivotal spring-cloud-services-dependencies

### ISSUE THREAD

**Issue by alwaysastudent** [spring-io/platform#574]
There is a good opportunity to compose all the cloud dependencies along with this BOM. 

- Please refer to the BOM for spring cloud dependencies under the artifact `org.springframework.cloud:spring-cloud-dependencies` - [link](https://github.com/spring-cloud/spring-cloud-release/blob/master/spring-cloud-dependencies/pom.xml)
- Please refer to the BOM for PCF spring cloud services under the artifact `io.pivotal.spring.cloud:spring-cloud-services-dependencies` - [link](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-dependencies/pom.xml)

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but we consider Spring Cloud to be at a higher level in the stack than the Platform. Please see #232 for more details.
