### ISSUE TITLE
Upgrade to curator version 2.12.0

### ISSUE THREAD

**Issue by anjo-swe** [spring-io/platform#605]
Current version: 2.11.1

Tickets in 2.12.0: https://issues.apache.org/jira/projects/CURATOR/versions/12338714

Main one impacting us https://issues.apache.org/jira/browse/CURATOR-200 (Remove references to guava library from public APIs)

**Comment by wilkinsona** [comment]
See #617

**Comment by anjo-swe** [comment]
Thanks
