### ISSUE TITLE
Add commons-configuration2

### ISSUE THREAD

**Issue by stonio** [spring-io/platform#702]
Can you consider adding following dependency in branch *brussels*?

```xml
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-configuration2</artifactId>
    <version>2.2</version>
</dependency>
```

**Comment by wilkinsona** [comment]
Unfortunately not, no. The Platform's scope is constrained to libraries that its Spring projects depend upon. None of them use commons-configuration2 so it's out of scope.
