### ISSUE TITLE
Broken link in Spring IO Platform page

### ISSUE THREAD

**Issue by stephane-deraco** [spring-io/platform#744]
In the https://platform.spring.io/platform/ page, the link for "Overview" (under "More information") is broken: it links to https://spring.io/platform which shows a 404.

(This issue was initially created in spring-io/sagan#820, which was not the correct place)

**Comment by wilkinsona** [comment]
Duplicates #743.

**Comment by bclozel** [comment]
Note: #743 updates the README and asks to change the link in the repository header. But it does not mention the https://platform.spring.io/platform/ page.

**Comment by wilkinsona** [comment]
Thanks, @blozel. We need to update the GitHub page to remove the Overview link. Then I think we should redirect https://spring.io/platform to https://platform.spring.io/platform. I'll do the former here. Perhaps we can use spring-io/sagan#820 for the latter?
