### ISSUE TITLE
Improve documentation to describe which version of platform to choose

### ISSUE THREAD

**Issue by boonware** [spring-io/platform#745]
The [Spring Cloud project page](http://projects.spring.io/spring-cloud/) describes which version of the BOM to choose for a given Spring Boot version. It would be helpful if the Platform project also documented which version of the BOM is compatible with which version of Spring Boot.

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but this doesn’t really make sense. Each version of the Platform builds on a specific version of Spring Boot and provides a superset if it’s dependency management.

**Comment by boonware** [comment]
@wilkinsona I get that, but the Platform documentation doesn't say which version of the BOM to select when you want a specific line of Spring Boot. I had to view the POM files to realize that [Brussels](http://central.maven.org/maven2/io/spring/platform/platform-bom/Brussels-SR7/platform-bom-Brussels-SR7.pom) is for Boot 1.5.X and [Athens](http://central.maven.org/maven2/io/spring/platform/platform-bom/Athens-SR6/platform-bom-Athens-SR6.pom) is for Boot 1.4.X. It would be helpful if the documentation clarified this.

**Comment by wilkinsona** [comment]
The documentation already contains [an appendix](https://docs.spring.io/platform/docs/Brussels-SR7/reference/htmlsingle/#appendix-dependency-versions) that lists all of the dependency versions, including Spring Boot.
