### ISSUE TITLE
Review and update list of removed dependencies in upgrading documentation

### ISSUE THREAD

**Issue by AlexCzar** [spring-io/platform#746]
Tried to upgrade project from `Brussels-SR3` to `Cairo-RC1` and project fails because gradle cannot resolve `spock-core` and `spock-spring` versions. I could not find anything in the documentation about removal of these dependencies, so it looks like a regression to me.

**Comment by wilkinsona** [comment]
This isn't a regression, but an omission in the documentation. Previously, the dependency management for Spock was inherited from Spring Boot. The dependency management [was removed in Spring Boot 2.0 M1](https://github.com/spring-projects/spring-boot/issues/9043). As a result, it's not included in Cairo (which builds on Boot 2.0).

I'll repurpose this issue to make sure that the Platform's documentation lists dependency management that's been removed indirectly.
