### ISSUE TITLE
Platform BOM `Cairo-RELEASE` downgrades `javax.ws.rs-api`

### ISSUE THREAD

**Issue by vpavic** [spring-io/platform#751]
Jersey `2.26`, which is provided by Boot `2.0.0.RELEASE` dependency management, depends on JAX-RS API `2.1` as can be seen [here](https://search.maven.org/remotecontent?filepath=org/glassfish/jersey/project/2.26/project-2.26.pom).

Platform BOM `Cairo-RELEASE` OTOH, explicitly declares version [`2.0.1`](https://github.com/spring-io/platform/blob/master/platform-bom/pom.xml#L101) of the same dependency.

Is there a reason for this? This means that if an existing Boot 2.0 app which uses Jersey, wants to use Platform BOM for dependency management, will have to manually upgrade `javax.ws.rs-api` to `2.1` (for example, to be able to use `javax.ws.rs.PATCH`),  which isn't the greatest user experience.

**Comment by wilkinsona** [comment]
No reason other than human error. It's a shame this wasn't caught in the RC phase.
