### ISSUE TITLE
jackson.version conflict Brussels-SR8 and Brussels-SR9

### ISSUE THREAD

**Issue by stijnhaezebrouck** [spring-io/platform#754]
spring-platform Brussels-SR8 parent spring.boot.dependencies-1.5.11.RELEASE defines a jackson.version property, which is 2.8.11.20180217.
This imports the com.fasterxml.jackson:jackson-bom of version 2.8.11.20180217.
The jackson-bom also defines a jackson.version, 2.8.11, which should import jackson-core version 2.8.11. That does not happen: our project extends from parent spring-platform, so jackson.version is defined to 2.8.11.20180217. Importing the jackson-bom from the spring boot parent does not redefine jackson.version, hence, maven tries to depend on jackson-core version 2.8.11.20180217 (which does not exist) instead of 2.8.11 (which does exist).
Hence, migrating to Brussels-SR8 breaks our build.
Sure, we can define a jackson.version ourselves, and set it to 2.8.11, but the whole idea to the spring platform boms, is that you do not need to manage those dependency versions yourself, right?

The problem is both appears in Brussels-SR8 and Brussels-SR9 (not yet in Brussels-SR7).

It would be better if spring.boot.dependencies would declare a jackon-bom.version instead of a jackson.version, avoiding the property conflict (as they have both different values).

**Comment by wilkinsona** [comment]
This configuration is inherited from Spring Boot (see https://github.com/spring-projects/spring-boot/issues/12790).
