### ISSUE TITLE
update spring-security-oauth.version 2.2.2.RELEASE to 2.3.3.RELEASE

### ISSUE THREAD

**Issue by yy306525121** [spring-io/platform#789]
update spring-security-oauth.version 2.2.2.RELEASE to 2.3.3.RELEASE

when i use spring-cloud-start-oauth2 2.0.0.RELEASE  it has some error

**Comment by wilkinsona** [comment]
No more minor or major versions of the Platform are planned and it isn’t appropriate to pick up a new minor version of a dependency in a maintenance release of the Platform.
